package Entity;
// Generated 13 oct. 2017 20:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Adherent generated by hbm2java
 */
@Entity
@Table(name="adherent"
    ,catalog="podium"
)
public class Adherent  implements java.io.Serializable {


     private Long numInsc;
     private String nom;
     private String prenom;
     private String dateNaiss;
     private String lieuNaiss;
     private long cin;
     private String adresse;
     private String metier;
     private long tel;
     private String parent;
     private String metierP;
     private long telP;
     private String dateInsc;
     private Pointage pointage;
     private Set paiements = new HashSet(0);
     private Set disciplines = new HashSet(0);

    public Adherent() {
    }

	
    public Adherent(String nom, String prenom, String dateNaiss, String lieuNaiss, long cin, String adresse, String metier, long tel, String parent, String metierP, long telP, String dateInsc) {
        this.nom = nom;
        this.prenom = prenom;
        this.dateNaiss = dateNaiss;
        this.lieuNaiss = lieuNaiss;
        this.cin = cin;
        this.adresse = adresse;
        this.metier = metier;
        this.tel = tel;
        this.parent = parent;
        this.metierP = metierP;
        this.telP = telP;
        this.dateInsc = dateInsc;
    }
    public Adherent(String nom, String prenom, String dateNaiss, String lieuNaiss, long cin, String adresse, String metier, long tel, String parent, String metierP, long telP, String dateInsc, Pointage pointage, Set paiements, Set disciplines) {
       this.nom = nom;
       this.prenom = prenom;
       this.dateNaiss = dateNaiss;
       this.lieuNaiss = lieuNaiss;
       this.cin = cin;
       this.adresse = adresse;
       this.metier = metier;
       this.tel = tel;
       this.parent = parent;
       this.metierP = metierP;
       this.telP = telP;
       this.dateInsc = dateInsc;
       this.pointage = pointage;
       this.paiements = paiements;
       this.disciplines = disciplines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="num_insc", unique=true, nullable=false)
    public Long getNumInsc() {
        return this.numInsc;
    }
    
    public void setNumInsc(Long numInsc) {
        this.numInsc = numInsc;
    }

    
    @Column(name="nom", nullable=false, length=500)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=500)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="date_naiss", nullable=false, length=500)
    public String getDateNaiss() {
        return this.dateNaiss;
    }
    
    public void setDateNaiss(String dateNaiss) {
        this.dateNaiss = dateNaiss;
    }

    
    @Column(name="lieu_naiss", nullable=false, length=500)
    public String getLieuNaiss() {
        return this.lieuNaiss;
    }
    
    public void setLieuNaiss(String lieuNaiss) {
        this.lieuNaiss = lieuNaiss;
    }

    
    @Column(name="cin", nullable=false)
    public long getCin() {
        return this.cin;
    }
    
    public void setCin(long cin) {
        this.cin = cin;
    }

    
    @Column(name="adresse", nullable=false, length=500)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="metier", nullable=false, length=500)
    public String getMetier() {
        return this.metier;
    }
    
    public void setMetier(String metier) {
        this.metier = metier;
    }

    
    @Column(name="tel", nullable=false)
    public long getTel() {
        return this.tel;
    }
    
    public void setTel(long tel) {
        this.tel = tel;
    }

    
    @Column(name="parent", nullable=false, length=500)
    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }

    
    @Column(name="metier_p", nullable=false, length=500)
    public String getMetierP() {
        return this.metierP;
    }
    
    public void setMetierP(String metierP) {
        this.metierP = metierP;
    }

    
    @Column(name="tel_p", nullable=false)
    public long getTelP() {
        return this.telP;
    }
    
    public void setTelP(long telP) {
        this.telP = telP;
    }

    
    @Column(name="date_insc", nullable=false, length=500)
    public String getDateInsc() {
        return this.dateInsc;
    }
    
    public void setDateInsc(String dateInsc) {
        this.dateInsc = dateInsc;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="adherent")
    public Pointage getPointage() {
        return this.pointage;
    }
    
    public void setPointage(Pointage pointage) {
        this.pointage = pointage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="adherent")
    public Set getPaiements() {
        return this.paiements;
    }
    
    public void setPaiements(Set paiements) {
        this.paiements = paiements;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pratiquer", catalog="podium", joinColumns = { 
        @JoinColumn(name="num_insc", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_disp", nullable=false, updatable=false) })
    public Set getDisciplines() {
        return this.disciplines;
    }
    
    public void setDisciplines(Set disciplines) {
        this.disciplines = disciplines;
    }




}


