package Entity;
// Generated 13 oct. 2017 20:33:40 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cheque generated by hbm2java
 */
@Entity
@Table(name="cheque"
    ,catalog="podium"
)
public class Cheque  implements java.io.Serializable {


     private ChequeId id;
     private Paiement paiement;
     private String dateVers;

    public Cheque() {
    }

    public Cheque(ChequeId id, Paiement paiement, String dateVers) {
       this.id = id;
       this.paiement = paiement;
       this.dateVers = dateVers;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="num", column=@Column(name="num", nullable=false) ), 
        @AttributeOverride(name="banque", column=@Column(name="banque", nullable=false, length=500) ), 
        @AttributeOverride(name="proprietaire", column=@Column(name="proprietaire", nullable=false, length=500) ) } )
    public ChequeId getId() {
        return this.id;
    }
    
    public void setId(ChequeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_p", nullable=false)
    public Paiement getPaiement() {
        return this.paiement;
    }
    
    public void setPaiement(Paiement paiement) {
        this.paiement = paiement;
    }

    
    @Column(name="date_vers", nullable=false, length=500)
    public String getDateVers() {
        return this.dateVers;
    }
    
    public void setDateVers(String dateVers) {
        this.dateVers = dateVers;
    }




}


