package Entity;
// Generated 13 oct. 2017 20:33:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChequeId generated by hbm2java
 */
@Embeddable
public class ChequeId  implements java.io.Serializable {


     private long num;
     private String banque;
     private String proprietaire;

    public ChequeId() {
    }

    public ChequeId(long num, String banque, String proprietaire) {
       this.num = num;
       this.banque = banque;
       this.proprietaire = proprietaire;
    }
   


    @Column(name="num", nullable=false)
    public long getNum() {
        return this.num;
    }
    
    public void setNum(long num) {
        this.num = num;
    }


    @Column(name="banque", nullable=false, length=500)
    public String getBanque() {
        return this.banque;
    }
    
    public void setBanque(String banque) {
        this.banque = banque;
    }


    @Column(name="proprietaire", nullable=false, length=500)
    public String getProprietaire() {
        return this.proprietaire;
    }
    
    public void setProprietaire(String proprietaire) {
        this.proprietaire = proprietaire;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChequeId) ) return false;
		 ChequeId castOther = ( ChequeId ) other; 
         
		 return (this.getNum()==castOther.getNum())
 && ( (this.getBanque()==castOther.getBanque()) || ( this.getBanque()!=null && castOther.getBanque()!=null && this.getBanque().equals(castOther.getBanque()) ) )
 && ( (this.getProprietaire()==castOther.getProprietaire()) || ( this.getProprietaire()!=null && castOther.getProprietaire()!=null && this.getProprietaire().equals(castOther.getProprietaire()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNum();
         result = 37 * result + ( getBanque() == null ? 0 : this.getBanque().hashCode() );
         result = 37 * result + ( getProprietaire() == null ? 0 : this.getProprietaire().hashCode() );
         return result;
   }   


}


