package Entity;
// Generated 13 oct. 2017 20:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discipline generated by hbm2java
 */
@Entity
@Table(name="discipline"
    ,catalog="podium"
)
public class Discipline  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String categorie;
     private String groupe;
     private Set paiements = new HashSet(0);
     private Set adherents = new HashSet(0);

    public Discipline() {
    }

	
    public Discipline(String nom, String categorie, String groupe) {
        this.nom = nom;
        this.categorie = categorie;
        this.groupe = groupe;
    }
    public Discipline(String nom, String categorie, String groupe, Set paiements, Set adherents) {
       this.nom = nom;
       this.categorie = categorie;
       this.groupe = groupe;
       this.paiements = paiements;
       this.adherents = adherents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=500)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="categorie", nullable=false, length=500)
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    
    @Column(name="groupe", nullable=false, length=500)
    public String getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(String groupe) {
        this.groupe = groupe;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discipline")
    public Set getPaiements() {
        return this.paiements;
    }
    
    public void setPaiements(Set paiements) {
        this.paiements = paiements;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="disciplines")
    public Set getAdherents() {
        return this.adherents;
    }
    
    public void setAdherents(Set adherents) {
        this.adherents = adherents;
    }




}


