package Entity;
// Generated 13 oct. 2017 20:33:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paiement generated by hbm2java
 */
@Entity
@Table(name="paiement"
    ,catalog="podium"
)
public class Paiement  implements java.io.Serializable {


     private int id;
     private Adherent adherent;
     private Discipline discipline;
     private User user;
     private Date dateP;
     private int nbrMois;
     private String montant;
     private String moyenP;
     private Set cheques = new HashSet(0);

    public Paiement() {
    }

	
    public Paiement(int id, Adherent adherent, Discipline discipline, User user, Date dateP, int nbrMois, String montant, String moyenP) {
        this.id = id;
        this.adherent = adherent;
        this.discipline = discipline;
        this.user = user;
        this.dateP = dateP;
        this.nbrMois = nbrMois;
        this.montant = montant;
        this.moyenP = moyenP;
    }
    public Paiement(int id, Adherent adherent, Discipline discipline, User user, Date dateP, int nbrMois, String montant, String moyenP, Set cheques) {
       this.id = id;
       this.adherent = adherent;
       this.discipline = discipline;
       this.user = user;
       this.dateP = dateP;
       this.nbrMois = nbrMois;
       this.montant = montant;
       this.moyenP = moyenP;
       this.cheques = cheques;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="num_insc", nullable=false)
    public Adherent getAdherent() {
        return this.adherent;
    }
    
    public void setAdherent(Adherent adherent) {
        this.adherent = adherent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_disp", nullable=false)
    public Discipline getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_p", nullable=false, length=19)
    public Date getDateP() {
        return this.dateP;
    }
    
    public void setDateP(Date dateP) {
        this.dateP = dateP;
    }

    
    @Column(name="nbr_mois", nullable=false)
    public int getNbrMois() {
        return this.nbrMois;
    }
    
    public void setNbrMois(int nbrMois) {
        this.nbrMois = nbrMois;
    }

    
    @Column(name="montant", nullable=false, length=500)
    public String getMontant() {
        return this.montant;
    }
    
    public void setMontant(String montant) {
        this.montant = montant;
    }

    
    @Column(name="moyen_p", nullable=false, length=500)
    public String getMoyenP() {
        return this.moyenP;
    }
    
    public void setMoyenP(String moyenP) {
        this.moyenP = moyenP;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paiement")
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }




}


