package Entity;
// Generated 13 oct. 2017 20:33:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Pointage generated by hbm2java
 */
@Entity
@Table(name="pointage"
    ,catalog="podium"
)
public class Pointage  implements java.io.Serializable {


     private long numInsc;
     private Adherent adherent;
     private int nbrPoints;

    public Pointage() {
    }

    public Pointage(Adherent adherent, int nbrPoints) {
       this.adherent = adherent;
       this.nbrPoints = nbrPoints;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="adherent"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="num_insc", unique=true, nullable=false)
    public long getNumInsc() {
        return this.numInsc;
    }
    
    public void setNumInsc(long numInsc) {
        this.numInsc = numInsc;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Adherent getAdherent() {
        return this.adherent;
    }
    
    public void setAdherent(Adherent adherent) {
        this.adherent = adherent;
    }

    
    @Column(name="nbr_points", nullable=false)
    public int getNbrPoints() {
        return this.nbrPoints;
    }
    
    public void setNbrPoints(int nbrPoints) {
        this.nbrPoints = nbrPoints;
    }




}


